spring:
  datasource:
    url: jdbc:mysql://161.9.0.208/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
  port: 8080

